Notestash-Admin/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Notestash_Admin.Controllers
{
    public class NotesController : Controller
    {
     // Display Notes
        [HttpGet]
        public ActionResult Notes_Data()
        {
            if (Session["Login"] == null)
            {
                return RedirectToAction("SignIn", "Login");
            }

            using (Notestash_Database_Entities db = new Notestash_Database_Entities())
            {
                var notes = db.tblNotes.ToList();
                return View(notes);
            }
        }
    }
}

Notestash-Admin/Controllers/RegisterController.cs
using Notestash_Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SecurityDriven.Inferno.Kdf;
using PBKDF2 = SecurityDriven.Inferno.Kdf.PBKDF2;
using SecurityDriven.Inferno.Extensions;
using static SecurityDriven.Inferno.SuiteB;
using static SecurityDriven.Inferno.Utils;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Notestash_Admin.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Display registration page.
        [HttpGet]
        public ActionResult SignUp()
        {
            if (Session["Login"] == null)
            {
                return RedirectToAction("SignIn", "Login");
            }

            return View();
        }
        // POST: Add an Admin through registration page.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp([Bind(Exclude = "IsEmailVerified,ActivationCode,ProfilePicture")]signUp User)
        {
            bool Status = false;
            bool Invalid = false;

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("BadRequest", "Registration failed!");
            }
            else
            {
                signUp ob = new signUp();
                string created = ob.Create(User);

                if (created == "exists")
                {
                    ModelState.AddModelError("EmailExist", "Email Already Exists!");
                }
                else if (created == "error")
                {
                    Invalid = true;
                    ViewBag.Invalid = Invalid;
                    ModelState.AddModelError("BadRequest", "Registration failed!");
                }
                else
                {
                    int i = created.IndexOf(" ");
                    int sizeOfCode = created.Length - i - 1;
                    string passedEmail = created.Substring(0, i);
                    string passedCode = created.Substring((i + 1), sizeOfCode);
                    SendVerificationLink(passedEmail, passedCode);
                    ModelState.AddModelError("Success", "Admin has been added successfully! Activation Code has been sent to his email id.");
                    Status = true;             
                    ViewBag.Status = Status;
                }
            }
            return View(User);
        }

        // Send email verification link.
        [NonAction]
        public void SendVerificationLink(string Email, string ActivationCode)
        {
            var verifyUrl = "/Register/VerifyAccount/" + ActivationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);
            var fromEmail = new MailAddress("suryakant.rocky@gmail.com", "Notestash");
            var toEmail = new MailAddress(Email);
            var fromEmailPassword = "suryasharma";
            string subject = "Your account is successfully created!";
            string body = "<br/><br/>Please click on the link below to activate your Notestash-Admin account." + "<br/><br/><a href='" + link + "'>" + link + "</a>";

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword),
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }

        // GET: Verify account on clicking on activation code sent in email.
        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {
           // bool Status = false;
            using (Notestash_Database_Entities db = new Notestash_Database_Entities())
            {
                bool deleted = false;
                bool expired = false;
                bool activated = false;
                var activate = db.tblUsers.Where(e => e.ActivationCode == new Guid(id)).FirstOrDefault();
                if (activate == null)
                {
                    deleted = true;
                    ViewBag.Deleted = deleted;
                    ModelState.AddModelError("Deleted", "Account deleted! Create Again!");
                    return View();
                }
                else
                {
                    DateTime expire = activate.Created_at.Value.AddDays(1);
                    DateTime present = DateTime.Now;
                    if (present >= expire)
                    {
                        expired = true;
                        ViewBag.Expired = expired;
                        ModelState.AddModelError("Expired", "Link Expired! Register Again!");
                        return View();
                    }
                    else
                    {
                        activate.IsEmailVerified = 1;
                        db.SaveChanges();
                        activated = true;
                        ViewBag.Activated = activated;
                        ModelState.AddModelError("Activated", "Congratulations! Account activated! You are also a Notestash admin now.");
                        return View();
                    }
                }
            }          
        }
    }
}

Notestash-Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body style="padding-top:0px">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <h4 class="navbar-brand" style="margin-left:10%">NOTESTASH ADMIN PANEL</h4>
        <h4><i class="fas fa-user-plus" title="ADD ADMIN" style="color:#fff;cursor:pointer;" onclick="location.href='@Url.Action("SignUp", "Register")'" ></i></h4>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation" style="">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <h5><a class="nav-link" href="#" onclick="location.href='@Url.Action("User_Data", "UserData")'">USERS<span class="sr-only">(current)</span></a></h5>
                </li>
                <li class="nav-item">
                    <h5><a class="nav-link" href="#" onclick="location.href='@Url.Action("Notes_Data", "Notes")'" >NOTES</a></h5>
                </li>
                <li class="nav-item">
                    <h5><a class="nav-link" href="#" style="cursor:pointer;" data-toggle="modal" data-target="#myModal">ABOUT</a></h5>
                </li>
            </ul>

            <!-- The Modal -->
            <div class="modal fade" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">NOTESTASH</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            @*@Html.Action("SignUp", "Register")*@

                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>


            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" style="margin-right:10px">Search</button>
                <input class="btn btn-secondary my-2 my-sm-0" type="button" value="Logout" onclick="location.href='@Url.Action("SignOut", "Login")'" />
            </form>
        </div>
    </nav>
    @*@*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div> *@
    <div class="container body-content">
        @RenderBody()
        @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>